# Generated by Django 5.2.5 on 2025-09-03 23:30

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCAPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('pcap_file', models.FileField(upload_to=analyzer.models.pcap_upload_path)),
                ('file_size', models.BigIntegerField()),
                ('llm_model', models.CharField(default='llama3', max_length=100)),
                ('packet_count', models.IntegerField(blank=True, null=True)),
                ('analysis_result', models.TextField(blank=True, null=True)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('error', 'Erro')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Análise PCAP',
                'verbose_name_plural': 'Análises PCAP',
                'ordering': ['-created_at'],
            },
        ),
    ]
