# Generated by Django 5.2.5 on 2025-10-16 16:30

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCAPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('pcap_file', models.FileField(upload_to=analyzer.models.pcap_upload_path)),
                ('file_size', models.BigIntegerField()),
                ('llm_model', models.CharField(default='llama3', max_length=100)),
                ('llm_host', models.CharField(default='127.0.0.1', help_text='Host/IP do serviço LLM', max_length=255)),
                ('llm_port', models.IntegerField(default=11434, help_text='Porta do serviço LLM')),
                ('packet_count', models.IntegerField(blank=True, null=True)),
                ('analysis_result', models.TextField(blank=True, null=True)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('error', 'Erro')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('malware_score', models.IntegerField(blank=True, help_text='Score de probabilidade de malware (0-100)', null=True)),
                ('risk_level', models.CharField(blank=True, help_text='Nível de risco calculado (CRÍTICO/ALTO/MÉDIO/BAIXO)', max_length=20, null=True)),
                ('threat_indicators', models.JSONField(blank=True, help_text='Indicadores de ameaça detectados em formato JSON', null=True)),
                ('network_patterns', models.JSONField(blank=True, help_text='Padrões de rede identificados', null=True)),
                ('malware_signatures', models.JSONField(blank=True, help_text='Assinaturas de malware detectadas', null=True)),
                ('temporal_analysis', models.JSONField(blank=True, help_text='Análise temporal de comportamento', null=True)),
                ('threat_intelligence', models.JSONField(blank=True, help_text='Correlação com threat intelligence', null=True)),
            ],
            options={
                'verbose_name': 'Análise PCAP',
                'verbose_name_plural': 'Análises PCAP',
                'ordering': ['-created_at'],
            },
        ),
    ]
