# Generated by Django 5.2.5 on 2025-09-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcapanalysis',
            name='llm_host',
            field=models.CharField(default='127.0.0.1', help_text='Host/IP do serviço LLM', max_length=255),
        ),
        migrations.AddField(
            model_name='pcapanalysis',
            name='llm_port',
            field=models.IntegerField(default=11434, help_text='Porta do serviço LLM'),
        ),
    ]
