# Generated by Django 5.2.1 on 2025-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcapanalysis",
            name="malware_score",
            field=models.IntegerField(
                blank=True,
                help_text="Score de probabilidade de malware (0-100)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcapanalysis",
            name="risk_level",
            field=models.CharField(
                blank=True,
                help_text="Nível de risco calculado (CRÍTICO/ALTO/MÉDIO/BAIXO)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcapanalysis",
            name="threat_indicators",
            field=models.JSONField(
                blank=True,
                help_text="Indicadores de ameaça detectados em formato JSON",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcapanalysis",
            name="network_patterns",
            field=models.JSONField(
                blank=True, help_text="Padrões de rede identificados", null=True
            ),
        ),
        migrations.AddField(
            model_name="pcapanalysis",
            name="malware_signatures",
            field=models.JSONField(
                blank=True, help_text="Assinaturas de malware detectadas", null=True
            ),
        ),
        migrations.AddField(
            model_name="pcapanalysis",
            name="temporal_analysis",
            field=models.JSONField(
                blank=True, help_text="Análise temporal de comportamento", null=True
            ),
        ),
        migrations.AddField(
            model_name="pcapanalysis",
            name="threat_intelligence",
            field=models.JSONField(
                blank=True, help_text="Correlação com threat intelligence", null=True
            ),
        ),
    ]
